In [25]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [26]:
dataset=pd.read_csv('/content/diabetes_data_upload.csv')
dataset

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [27]:
data=dataset.copy()

In [28]:
data.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [29]:
data.columns

Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'],
      dtype='object')

In [30]:
df_dummies = pd.get_dummies(data, columns=['Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'], drop_first=True)

In [31]:
df_dummies=df_dummies.astype(int)

In [32]:
#Creating dummies in form of 1,0
df_dummies


Age  Gender_Male  Polyuria_Yes  Polydipsia_Yes  sudden weight loss_Yes  \
0     40            1             0               1                       0   
1     58            1             0               0                       0   
2     41            1             1               0                       0   
3     45            1             0               0                       1   
4     60            1             1               1                       1   
..   ...          ...           ...             ...                     ...   
515   39            0             1               1                       1   
516   48            0             1               1                       1   
517   58            0             1               1                       1   
518   32            0             0               0                       0   
519   42            1             0               0                       0   

     weakness_Yes  Polyphagia_Yes  Genital thrush_Yes  visual blurring_Yes  \
0               1               0                   0                    0   
1               1               0                   0                    1   
2               1               1                   0                    0   
3               1               1                   1                    0   
4               1               1                   0                    1   
..            ...             ...                 ...                  ...   
515             0               1                   0                    0   
516             1               1                   0                    0   
517             1               1                   0                    1   
518             1               0                   0                    1   
519             0               0                   0                    0   

     Itching_Yes  Irritability_Yes  delayed healing_Yes  partial paresis_Yes  \
0              1                 0                    1                    0   
1              0                 0                    0                    1   
2              1                 0                    1                    0   
3              1                 0                    1                    0   
4              1                 1                    1                    1   
..           ...               ...                  ...                  ...   
515            1                 0                    1                    1   
516            1                 1                    1                    1   
517            0                 0                    0                    1   
518            1                 0                    1                    0   
519            0                 0                    0                    0   

     muscle stiffness_Yes  Alopecia_Yes  Obesity_Yes  class_Positive  
0                       1             1            1               1  
1                       0             1            0               1  
2                       1             1            0               1  
3                       0             0            0               1  
4                       1             1            1               1  
..                    ...           ...          ...             ...  
515                     0             0            0               1  
516                     0             0            0               1  
517                     1             0            1               1  
518                     0             1            0               0  
519                     0             0            0               0  

[520 rows x 17 columns]

In [33]:
#Separating data into input and output variable and checking correlation
data=df_dummies
X=data.drop(columns=['class_Positive'])
y=data[['class_Positive']]
X.corr()

Age  Gender_Male  Polyuria_Yes  Polydipsia_Yes  \
Age                     1.000000     0.062872      0.199781        0.137382   
Gender_Male             0.062872     1.000000     -0.268894       -0.312262   
Polyuria_Yes            0.199781    -0.268894      1.000000        0.598609   
Polydipsia_Yes          0.137382    -0.312262      0.598609        1.000000   
sudden weight loss_Yes  0.064808    -0.281840      0.447207        0.405965   
weakness_Yes            0.224596    -0.124490      0.263000        0.332453   
Polyphagia_Yes          0.315577    -0.219968      0.373873        0.316839   
Genital thrush_Yes      0.096519     0.208961      0.087273        0.028081   
visual blurring_Yes     0.402729    -0.208092      0.235095        0.331250   
Itching_Yes             0.296559    -0.052496      0.088289        0.128716   
Irritability_Yes        0.201625    -0.013735      0.237740        0.203446   
delayed healing_Yes     0.257501    -0.101978      0.149873        0.115691   
partial paresis_Yes     0.232742    -0.332288      0.441664        0.442249   
muscle stiffness_Yes    0.307703    -0.090542      0.152938        0.180723   
Alopecia_Yes            0.321691     0.327871     -0.144192       -0.310964   
Obesity_Yes             0.140458    -0.005396      0.126567        0.098691   

                        sudden weight loss_Yes  weakness_Yes  Polyphagia_Yes  \
Age                                   0.064808      0.224596        0.315577   
Gender_Male                          -0.281840     -0.124490       -0.219968   
Polyuria_Yes                          0.447207      0.263000        0.373873   
Polydipsia_Yes                        0.405965      0.332453        0.316839   
sudden weight loss_Yes                1.000000      0.282884        0.243511   
weakness_Yes                          0.282884      1.000000        0.180266   
Polyphagia_Yes                        0.243511      0.180266        1.000000   
Genital thrush_Yes                    0.089858      0.027780       -0.063712   
visual blurring_Yes                   0.068754      0.301043        0.293545   
Itching_Yes                          -0.004516      0.309440        0.144390   
Irritability_Yes                      0.140340      0.146698        0.239466   
delayed healing_Yes                   0.088140      0.335507        0.263980   
partial paresis_Yes                   0.264014      0.272982        0.373569   
muscle stiffness_Yes                  0.109756      0.263164        0.320031   
Alopecia_Yes                         -0.202727      0.090490       -0.053498   
Obesity_Yes                           0.169294      0.045665        0.029785   

                        Genital thrush_Yes  visual blurring_Yes  Itching_Yes  \
Age                               0.096519             0.402729     0.296559   
Gender_Male                       0.208961            -0.208092    -0.052496   
Polyuria_Yes                      0.087273             0.235095     0.088289   
Polydipsia_Yes                    0.028081             0.331250     0.128716   
sudden weight loss_Yes            0.089858             0.068754    -0.004516   
weakness_Yes                      0.027780             0.301043     0.309440   
Polyphagia_Yes                   -0.063712             0.293545     0.144390   
Genital thrush_Yes                1.000000            -0.148408     0.125336   
visual blurring_Yes              -0.148408             1.000000     0.291191   
Itching_Yes                       0.125336             0.291191     1.000000   
Irritability_Yes                  0.160551             0.077095     0.114006   
delayed healing_Yes               0.136111             0.177767     0.453316   
partial paresis_Yes              -0.195612             0.364156     0.116669   
muscle stiffness_Yes             -0.100188             0.412369     0.215575   
Alopecia_Yes                      0.204847             0.014604     0.266506   
Obesity_Yes                       0.053828  

In [34]:
#Dropping columns with high correlation
X=X.drop(columns=['Polydipsia_Yes','Polyuria_Yes','visual blurring_Yes','Itching_Yes'])

In [35]:
#Standardizing X variables
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-0.6613669 ,  0.76509206, -0.84626923, ...,  1.29099445,
         1.38022749,  2.21564684],
       [ 0.82136224,  0.76509206, -0.84626923, ..., -0.77459667,
         1.38022749, -0.45133547],
       [-0.57899306,  0.76509206, -0.84626923, ...,  1.29099445,
         1.38022749, -0.45133547],
       ...,
       [ 0.82136224, -1.30703226,  1.18165704, ...,  1.29099445,
        -0.72451824,  2.21564684],
       [-1.32035762, -1.30703226, -0.84626923, ..., -0.77459667,
         1.38022749, -0.45133547],
       [-0.49661921,  0.76509206, -0.84626923, ..., -0.77459667,
        -0.72451824, -0.45133547]])

In [36]:
X = pd.DataFrame(X, columns=['Age','Gender_Male','sudden weight loss_Yes','weakness_Yes','Polyphagia_Yes','Genital thrush_Yes','Irritability_Yes','delayed healing_Yes','partial paresis_Yes','muscle stiffness_Yes','Alopecia_Yes','Obesity_Yes'])
X

Age  Gender_Male  sudden weight loss_Yes  weakness_Yes  \
0   -0.661367     0.765092               -0.846269      0.839594   
1    0.821362     0.765092               -0.846269      0.839594   
2   -0.578993     0.765092               -0.846269      0.839594   
3   -0.249498     0.765092                1.181657      0.839594   
4    0.986110     0.765092                1.181657      0.839594   
..        ...          ...                     ...           ...   
515 -0.743741    -1.307032                1.181657     -1.191052   
516 -0.002376    -1.307032                1.181657      0.839594   
517  0.821362    -1.307032                1.181657      0.839594   
518 -1.320358    -1.307032               -0.846269      0.839594   
519 -0.496619     0.765092               -0.846269     -1.191052   

     Polyphagia_Yes  Genital thrush_Yes  Irritability_Yes  \
0         -0.915126           -0.535844         -0.565506   
1         -0.915126           -0.535844         -0.565506   
2          1.092746           -0.535844         -0.565506   
3          1.092746            1.866215         -0.565506   
4          1.092746           -0.535844          1.768328   
..              ...                 ...               ...   
515        1.092746           -0.535844         -0.565506   
516        1.092746           -0.535844          1.768328   
517        1.092746           -0.535844         -0.565506   
518       -0.915126           -0.535844         -0.565506   
519       -0.915126           -0.535844         -0.565506   

     delayed healing_Yes  partial paresis_Yes  muscle stiffness_Yes  \
0               1.084312            -0.869918              1.290994   
1              -0.922244             1.149534             -0.774597   
2               1.084312            -0.869918              1.290994   
3               1.084312            -0.869918             -0.774597   
4               1.084312             1.149534              1.290994   
..                   ...                  ...                   ...   
515             1.084312             1.149534             -0.774597   
516             1.084312             1.149534             -0.774597   
517            -0.922244             1.149534              1.290994   
518             1.084312            -0.869918             -0.774597   
519            -0.922244            -0.869918             -0.774597   

     Alopecia_Yes  Obesity_Yes  
0        1.380227     2.215647  
1        1.380227    -0.451335  
2        1.380227    -0.451335  
3       -0.724518    -0.451335  
4        1.380227     2.215647  
..            ...          ...  
515     -0.724518    -0.451335  
516     -0.724518    -0.451335  
517     -0.724518     2.215647  
518      1.380227    -0.451335  
519     -0.724518    -0.451335  

[520 rows x 12 columns]

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size =0.7)

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

model = LogisticRegression()
model.fit(X_train, y_train)

# Making predictions
y_pred = model.predict(X_test)

# Calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculating confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.8397435897435898
Confusion Matrix:
[[50 12]
 [13 81]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [39]:
from sklearn.tree import DecisionTreeClassifier
model= DecisionTreeClassifier(criterion='entropy', random_state=0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9551282051282052
Confusion Matrix:
[[58  4]
 [ 3 91]]


In [40]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

<ipython-input-40-793256884b89>:3: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



Accuracy: 0.9423076923076923
Confusion Matrix:
[[55  7]
 [ 2 92]]


In [41]:
from sklearn.neighbors import KNeighborsClassifier
k = 5  # Number of neighbors
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.8782051282051282
Confusion Matrix:
[[55  7]
 [12 82]]


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



In [42]:
pip install dash

In [44]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
from io import BytesIO
import base64

def train_model(X_train, y_train):
    model = DecisionTreeClassifier(criterion='entropy', random_state=0)
    model.fit(X_train, y_train)
    return model

def plot_confusion_matrix(conf_matrix):
    fig, ax = plt.subplots()
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Class 0', 'Class 1'],
                yticklabels=['Class 0', 'Class 1'], ax=ax)
    ax.set_xlabel('Predicted Label')
    ax.set_ylabel('True Label')
    ax.set_title('Confusion Matrix')

    buf = BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)

    img_str = base64.b64encode(buf.getvalue()).decode('utf-8')
    plt.close(fig)
    return img_str

app = dash.Dash(__name__)


model = train_model(X_train, y_train)

app.layout = html.Div([
    html.H1('Decision Tree Classifier'),

    dcc.Input(id='age', type='number', placeholder='Age'),
    dcc.Checklist(id='gender_male', options=[{'label': 'Gender: Male', 'value': 1}]),
    dcc.Checklist(id='sudden_weight_loss', options=[{'label': 'Sudden Weight Loss', 'value': 1}]),
    dcc.Checklist(id='weakness', options=[{'label': 'Weakness', 'value': 1}]),
    dcc.Checklist(id='polyphagia', options=[{'label': 'Polyphagia', 'value': 1}]),
    dcc.Checklist(id='genital_thrush', options=[{'label': 'Genital Thrush', 'value': 1}]),
    dcc.Checklist(id='irritability', options=[{'label': 'Irritability', 'value': 1}]),
    dcc.Checklist(id='delayed_healing', options=[{'label': 'Delayed Healing', 'value': 1}]),
    dcc.Checklist(id='partial_paresis', options=[{'label': 'Partial Paresis', 'value': 1}]),
    dcc.Checklist(id='muscle_stiffness', options=[{'label': 'Muscle Stiffness', 'value': 1}]),
    dcc.Checklist(id='alopecia', options=[{'label': 'Alopecia', 'value': 1}]),
    dcc.Checklist(id='obesity', options=[{'label': 'Obesity', 'value': 1}]),

    html.Button('Predict', id='predict-button', n_clicks=0),

    html.Div(id='prediction-output'),
    html.Div(id='accuracy-output'),
    html.Img(id='conf-matrix-plot')
])

@app.callback(
    [Output('prediction-output', 'children'),
     Output('accuracy-output', 'children'),
     Output('conf-matrix-plot', 'src')],
    [Input('predict-button', 'n_clicks')],
    [Input('age', 'value'),
     Input('gender_male', 'value'),
     Input('sudden_weight_loss', 'value'),
     Input('weakness', 'value'),
     Input('polyphagia', 'value'),
     Input('genital_thrush', 'value'),
     Input('irritability', 'value'),
     Input('delayed_healing', 'value'),
     Input('partial_paresis', 'value'),
     Input('muscle_stiffness', 'value'),
     Input('alopecia', 'value'),
     Input('obesity', 'value')]
)
def update_output(n_clicks, age, gender_male,  sudden_weight_loss, weakness,
                   polyphagia, genital_thrush, irritability,
                   delayed_healing, partial_paresis, muscle_stiffness, alopecia, obesity):

    if n_clicks > 0:
        input_data = np.array([[
            age if age is not None else 0,
            1 if gender_male else 0,
            1 if sudden_weight_loss else 0,
            1 if weakness else 0,
            1 if polyphagia else 0,
            1 if genital_thrush else 0,
            1 if irritability else 0,
            1 if delayed_healing else 0,
            1 if partial_paresis else 0,
            1 if muscle_stiffness else 0,
            1 if alopecia else 0,
            1 if obesity else 0
        ]])

        prediction = model.predict(input_data)[0]

        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        conf_matrix = confusion_matrix(y_test, y_pred)

        conf_matrix_plot = plot_confusion_matrix(conf_matrix)

        return (f'Prediction: {"Positive" if prediction == 1 else "Negative"}',
                f'Accuracy: {accuracy:.2f}',
                f'data:image/png;base64,{conf_matrix_plot}')

    return "", "", ""

if __name__ == '__main__':
    app.run_server(debug=True)


<IPython.core.display.Javascript object>